import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;
// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes



class CodegenLoader extends AssetLoader {
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String, dynamic> ar = {
    "ok": "تم",
    "sign_in": "تسجيل الدخول",
    "have_no_account": "ليس لديك حساب؟ ",
    "sign_up_now": "أنشئ حساب الان!",
    "forget_password1": "نسيت كلمة المرور؟ ",
    "click_here": "اضغط هنا",
    "email": "البريد الالكتروني",
    "password": "كلمة المرور",
    "sign_up": "إنشاء حساب",
    "login_now": "سجل الدخول الان!",
    "first_name": "الاسم الاول",
    "last_name": "الاسم الاخير",
    "phone": "رقم الهاتف",
    "have_account": "لديك حساب بالفعل؟ ",
    "by_signing": "بالتسجيل فإنك توافق على ",
    "our": "سياسة البيانات",
    "terms": "وسياسة ملفات تعريف الارتباط الخاصة بنا",
    "forget_password2": "نسيت كلمة المرور",
    "enter_mobile": "ادخل رقم الهاتف",
    "enter_mail": "ادخل البريد الالكتروني",
    "send_code": "ارسال الرمز",
    "no_mobile": "لا يمكنك الوصول لهاتفك؟ ",
    "use_mail": "استخدم البريد الالكتروني",
    "use_mobile": "أو استخدم رقم الهاتف",
    "we_sent_code": "لقد ارسلنا الرمز الى هاتفك *********965",
    "enter_code": "ادخل الرمز",
    "new_password": "كلمة المرور الجديدة",
    "confirm_new_password": "تأكيد كلمة المرور الجديدة",
    "reset_password": "إعادة تعيين كلمة المرور",
    "you_registered": "تم إنشاء الحساب بنجاح",
    "wait_for_approval": "انتظر الموافقة من المشرف",
    "home": "الرئيسية",
    "wallet": "المحفظة",
    "notification": "الإشعارات",
    "settings": "الإعدادات",
    "contact_us": "اتصل بنا",
    "about_us": "معلومات عنا",
    "Categories": "الماركات",
    "Cart": "السله",
    "Clients": "العملاء",
    "Profile": "الملف الشخصي",
    "logout": "تسجيل الخروج",
    "our_brands": "علاماتنا التجارية",
    "your_clients": "عملاؤك",
    "empty_cart": "عربة التسوق الخاصة بك تبدو فارغة",
    "add_some_prods": "أضف بعض المنتجات",
    "view_client": "عرض بيانات العميل",
    "mobile_number": "رقم الموبايل",
    "address_book": "دفتر عناوين العميل",
    "client_orders": "طلبات العميل",
    "orders": "الطلبات",
    "order_number": "رقم الطلب",
    "total_price": "السعر الكلي",
    "delivering": "جاري التوصيل",
    "completed": "تم التوصيل",
    "canceled": "تم الإلغاء",
    "egp": "ج.م",
    "wallet_button1":"مدفوعات المندوب",
    "wallet_button2":"مدفوعات العميل",
    "wallet_button3":"التحويلات النقدية",
    "no_results": "لا توجد نتائج",
    "language": "اللغة",
    "lang": "عربي",
    "invite": "ادعو اصدقاءك",
    "enter_message": "اكتب رسالتك",
    "send": "ارسل",
    "copyrights": "حقوق النشر",
    "version": "اصدار 1.04",
    "all_rights": "جميع الحقوق محفوظة للمتحدة للصناعات الغذائية",
    "designed_by": "تصميم وتطوير:"
  };
  static const Map<String, dynamic> en = {
    "Profile": "Profile",
    "Clients": "Clients",
    "Cart": "Cart",
    "Categories": "Categories",
    "ok": "ok",
    "sign_in": "Sign in",
    "have_no_account": "Don't have an account? ",
    "sign_up_now": "Sign up now!",
    "forget_password1": "Forgot your password? ",
    "click_here": "Click here",
    "email": "E-mail",
    "password": "Password",
    "sign_up": "Sign up",
    "login_now": "Sign in now!",
    "first_name": "First Name",
    "last_name": "last Name",
    "phone": "Phone",
    "have_account": "Already have an account? ",
    "by_signing": "by signing up you agree to ",
    "our": "our",
    "terms": "terms data policy and cookies policy",
    "forget_password2": "Forgot Password",
    "enter_mobile": "Enter your mobile phone",
    "enter_mail": "Enter your Email",
    "send_code": "Send Code",
    "no_mobile": "can't reach your mobile? ",
    "use_mail": "use your email",
    "use_mobile": "Or use your mobile",
    "we_sent_code": "We have sent you a code to your mobile *********965",
    "enter_code": "Enter the code",
    "new_password": "New Password",
    "confirm_new_password": "Confirm New Password",
    "reset_password": "Reset Password",
    "you_registered": "You have been registered",
    "wait_for_approval": "wait for the approval from the admin",
    "home": "Home",
    "wallet": "Wallet",
    "notification": "Notification",
    "settings": "Settings",
    "contact_us": "Contact us",
    "about_us": "About us",
    "logout": "Logout",
    "our_brands": "Our Brands",
    "your_clients": "Your Clients",
    "empty_cart": "Your cart looks empty",
    "add_some_prods": "Add Some Products",
    "view_client": "View Client",
    "mobile_number": "Mobile Number",
    "address_book": "Client address book",
    "client_orders": "Client Orders",
    "add_new_order": "Add new order",
    "orders": "Orders",
    "order_number": "Order number",
    "total_price": "Total price",
    "delivering": "Delivering",
    "completed": "Completed",
    "canceled": "Canceled",
    "egp": "EGP",
    "wallet_button1":"Seller Payments",
    "wallet_button2":"Customer Payments",
    "wallet_button3":"Money Transfer",
    "no_results": "No Results",
    "language": "Language",
    "lang": "English",
    "invite": "Invite your Friends",
    "enter_message": "Enter your message",
    "send": "Send",
    "copyrights": "Copyrights",
    "version": "Version 1.04",
    "all_rights": "All Rights Reserved to United food industry",
    "designed_by": "Designed and Developed by:"
  };
  static const Map<String, Map<String, dynamic>> mapLocales = {
    "ar": ar,
    "en": en
  };
}
